APP = Port+View
APP_PATH = apps

PROGRAMS = Port+View
ICON = 24x12_ViewApp
GRAPHICS = ViewCore ViewTop ViewBot ViewP1 ViewP2 ViewP3 ViewP4 ViewPA ViewPB \
           ViewPC ViewPD tdef t010 t020 t030 t040 t050 t060 t061 t070 t071 \
           t080 t081 t160 t290 t291 t292 t300 t320 t321 t330 t331 t332 \
           PE_input PE_output

ViewCore_SOURCE = View_Core
ViewTop_SOURCE = P0_top
ViewBot_SOURCE = P0_bot
ViewP1_SOURCE = P1
ViewP2_SOURCE = P2
ViewP3_SOURCE = P3
ViewP4_SOURCE = P4
ViewPA_SOURCE = PA
ViewPB_SOURCE = PB
ViewPC_SOURCE = PC
ViewPD_SOURCE = PD
tdef_SOURCE = other
t010_SOURCE = NXT_device
t020_SOURCE = NXT_device
t030_SOURCE = NXT_device
t040_SOURCE = NXT_device
t050_SOURCE = NXT_device
t060_SOURCE = temp_c
t061_SOURCE = temp_f
t070_SOURCE = lrg_motor_d
t071_SOURCE = lrg_motor
t080_SOURCE = med_motor_d
t081_SOURCE = med_motor
t160_SOURCE = touch
t290_SOURCE = color_ref
t291_SOURCE = color_amb
t292_SOURCE = color_col
t300_SOURCE = us_prox
t320_SOURCE = gyro_a
t321_SOURCE = gyro_rate
t330_SOURCE = ir_prox
t331_SOURCE = ir_bpos
t332_SOURCE = ir_bbut

include ../rules.mk
