#! /bin/bash
#
#   UPDATE ALL
#

cd Bluetooth
./update
cd ..

cd "Brick Datalog"
./update
cd ..

cd "Brick Info"
./update
cd ..

cd "Brick Program"
./update
cd ..

cd "IR Control"
./update
cd ..

cd "Motor Control"
./update
cd ..

cd "Port View"
./update
cd ..

cd Sleep
./update
cd ..

cd Volume
./update
cd ..

cd WiFi
./update
cd ..

cd ui
./update
cd ..

cd c_ui
./update
cd ..

#cd TEST
#./update
#cd ..

#cd SelfTest
#./update
#cd ..









#cd tst
#./update
#cd ..

#cd Debug
#./update
#cd ..

#cd Demo
#./update
#cd ..

#cd Test
#./update
#cd ..



