APP = Brick+Program
APP_PATH = apps

PROGRAMS = Brick+Program template
ICON = 24x12_ProgApp
GRAPHICS = block_bin 144x116_POP6 Blocklink BlockAdd ToLib PrgOpen PrgOpenH \
	   PrgSave PrgSaveH ProgNav ProgNavdot LibToProg LIBH1 LIBH2 StartBLKn \
	   StartBLKs RepBlkn RepBlks RepBlkh A_LoopP1 A_LoopP2 A_LoopP3 \
	   A_LoopP4 A_LoopP5 A_LoopP6 A_LoopP7 BLKn BLKs BLKh Pn_1 Ps_1 Ph_1 \
	   Pn_2 Ps_2 Ph_2 Pn_3 Ps_3 Ph_3 Pn_4 Ps_4 Ph_4 Pn_a Ps_a Ph_a Pn_b \
	   Ps_b Ph_b Pn_bc Ps_bc Ph_bc Pn_c Ps_c Ph_c Pn_d Ps_d Ph_d A_numP01 \
	   A_numP02 A_numP03 A_numP04 A_numP05 A_numP06 A_numP07 A_numP08 \
	   A_numP09 A_numP10 A_numP11 A_numP12 A_numP13 A_Move A_MoveP1 \
	   A_MoveP2 A_MoveP3 A_MoveP4 A_MoveP5 A_MoveP6 A_MoveP7 A_MoveP8 \
	   A_MoveP9 A_Lmot A_motP1 A_motP2 A_motP3 A_motP4 A_motP5 A_motP6 \
	   A_motP7 A_motP8 A_motP9 A_Mmot A_BLit A_BLitP1 A_BLitP2 A_BLitP3 \
	   A_BLitP4 A_BLitP5 A_BLitP6 A_BLitP7 A_Snd A_Disp OnBrickImage01 \
	   OnBrickImage02 OnBrickImage03 OnBrickImage04 OnBrickImage05 \
	   OnBrickImage06 OnBrickImage07 OnBrickImage08 OnBrickImage09 \
	   OnBrickImage10 OnBrickImage11 OnBrickImage12 W_Touch W_TouchP1 \
	   W_TouchP2 W_TouchP3 W_colref W_colrefP01 W_colrefP02 W_colrefP03 \
	   W_colrefP04 W_colrefP05 W_colrefP06 W_colrefP07 W_colrefP08 \
	   W_colrefP09 W_colrefP10 W_colrefP11 W_colrefP12 W_colrefP13 \
	   W_colrefP14 W_colrefP15 W_colrefP16 W_colcol W_colcolP1 W_colcolP2 \
	   W_colcolP3 W_colcolP4 W_colcolP5 W_colcolP6 W_colcolP7 W_colcolP8 \
	   W_irprox W_irproxP01 W_irproxP02 W_irproxP03 W_irproxP04 \
	   W_irproxP05 W_irproxP06 W_irproxP07 W_irproxP08 W_irrem W_irremP01 \
	   W_irremP02 W_irremP03 W_irremP04 W_irremP05 W_irremP06 W_us W_usP01 \
	   W_usP02 W_usP03 W_usP04 W_usP05 W_usP06 W_usP07 W_usP08 W_usP09 \
	   W_usP10 W_usP11 W_usP12 W_usP13 W_usP14 W_usP15 W_usP16 W_gyro \
	   W_angP01 W_angP02 W_angP03 W_angP04 W_angP05 W_angP06 W_angP07 \
	   W_angP08 W_angP09 W_angP10 W_angP11 W_angP12 W_mmot W_temp \
	   W_tempP01 W_tempP02 W_tempP03 W_tempP04 W_tempP05 W_tempP06 \
	   W_tempP07 W_tempP08 W_tempP09 W_tempP10 W_tempP11 W_tempP12 \
	   W_tempP13 W_tempP14 W_tempP15 W_tempP16 W_bbut W_bbutP1 W_bbutP2 \
	   W_bbutP3 W_bbutP4 W_bbutP5 W_time W_timeP1 W_timeP2 W_timeP3 \
	   W_timeP4 W_timeP5 W_timeP6 W_timeP7 W_timeP8
SOUNDS = GeneralAlarm OnBrickSound01 OnBrickSound02 OnBrickSound03 \
         OnBrickSound04 OnBrickSound05 OnBrickSound06 OnBrickSound07 \
         OnBrickSound08 OnBrickSound09 OnBrickSound10 OnBrickSound11 \
         OnBrickSound12

include ../rules.mk
