
/* File: eggdbusstartservicebynamereply.h
 *
 * Generated by eggdbus-binding-tool 0.6. Do not edit.
 */

#ifndef __EGG_DBUS_START_SERVICE_BY_NAME_REPLY_H
#define __EGG_DBUS_START_SERVICE_BY_NAME_REPLY_H

#include <glib-object.h>
#include <gio/gio.h>
#include <eggdbus/eggdbustypes.h>
#include <eggdbus/eggdbusinterface.h>
#include <eggdbus/eggdbusinterfaceproxy.h>
#include <eggdbus/eggdbusrequestnameflags.h>
#include <eggdbus/eggdbusrequestnamereply.h>
#include <eggdbus/eggdbusreleasenamereply.h>
#include <eggdbus/eggdbusstartservicebynamereply.h>

G_BEGIN_DECLS

GType egg_dbus_start_service_by_name_reply_get_type (void) G_GNUC_CONST;

#define EGG_DBUS_TYPE_START_SERVICE_BY_NAME_REPLY (egg_dbus_start_service_by_name_reply_get_type ())

/**
 * EggDBusStartServiceByNameReply:
 * @EGG_DBUS_START_SERVICE_BY_NAME_REPLY_SUCCESS: The service was successfully started.
 * @EGG_DBUS_START_SERVICE_BY_NAME_REPLY_ALREADY_RUNNING: A connection already owns the given name.
 *
 * Return values for the egg_dbus_bus_start_service_by_name() method.
 */
typedef enum
{
  EGG_DBUS_START_SERVICE_BY_NAME_REPLY_SUCCESS = 1,
  EGG_DBUS_START_SERVICE_BY_NAME_REPLY_ALREADY_RUNNING = 2,
} EggDBusStartServiceByNameReply;

G_END_DECLS

#endif /* __EGG_DBUS_START_SERVICE_BY_NAME_REPLY_H */
