
/* File: eggdbusrequestnamereply.h
 *
 * Generated by eggdbus-binding-tool 0.6. Do not edit.
 */

#ifndef __EGG_DBUS_REQUEST_NAME_REPLY_H
#define __EGG_DBUS_REQUEST_NAME_REPLY_H

#include <glib-object.h>
#include <gio/gio.h>
#include <eggdbus/eggdbustypes.h>
#include <eggdbus/eggdbusinterface.h>
#include <eggdbus/eggdbusinterfaceproxy.h>
#include <eggdbus/eggdbusrequestnameflags.h>
#include <eggdbus/eggdbusrequestnamereply.h>
#include <eggdbus/eggdbusreleasenamereply.h>
#include <eggdbus/eggdbusstartservicebynamereply.h>

G_BEGIN_DECLS

GType egg_dbus_request_name_reply_get_type (void) G_GNUC_CONST;

#define EGG_DBUS_TYPE_REQUEST_NAME_REPLY (egg_dbus_request_name_reply_get_type ())

/**
 * EggDBusRequestNameReply:
 * @EGG_DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER: The caller is now the primary owner of the name, replacing any previous owner. Either the name had no owner before, or the caller specified %EGG_DBUS_REQUEST_NAME_FLAGS_REPLACE_EXISTING and the current owner specified %EGG_DBUS_REQUEST_NAME_FLAGS_ALLOW_REPLACEMENT.
 * @EGG_DBUS_REQUEST_NAME_REPLY_IN_QUEUE: The name already had an owner, %EGG_DBUS_REQUEST_NAME_FLAGS_DO_NOT_QUEUE was not specified, and either the current owner did not specify %EGG_DBUS_REQUEST_NAME_FLAGS_ALLOW_REPLACEMENT or the requesting application did not specify %EGG_DBUS_REQUEST_NAME_FLAGS_REPLACE_EXISTING.
 * @EGG_DBUS_REQUEST_NAME_REPLY_EXISTS: The name already has an owner, %EGG_DBUS_REQUEST_NAME_FLAGS_DO_NOT_QUEUE was specified, and either %EGG_DBUS_REQUEST_NAME_FLAGS_ALLOW_REPLACEMENT was not specified by the current owner, or %EGG_DBUS_REQUEST_NAME_FLAGS_REPLACE_EXISTING was not specified by the requesting application.
 * @EGG_DBUS_REQUEST_NAME_REPLY_ALREADY_OWNED: The application trying to request ownership of a name is already the owner of it
 *
 * Return values for the egg_dbus_bus_request_name() method
 */
typedef enum
{
  EGG_DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER = 1,
  EGG_DBUS_REQUEST_NAME_REPLY_IN_QUEUE = 2,
  EGG_DBUS_REQUEST_NAME_REPLY_EXISTS = 3,
  EGG_DBUS_REQUEST_NAME_REPLY_ALREADY_OWNED = 4,
} EggDBusRequestNameReply;

G_END_DECLS

#endif /* __EGG_DBUS_REQUEST_NAME_REPLY_H */
