#! /bin/bash

#*** APPLICATION *************************************************************

path="prjs"
dir="TEST"

#*** HOST ********************************************************************

lms_to_rbf="../adk/cmp"
xbm_to_rgf="../adk/bmp"
bmp_to_xbm="convert"

#*** TARGET ******************************************************************

am1808="../../lms2012/Linux_AM1808"
x86="../../lms2012/Linux_X86"
nfs="../../../../am1808/DaVinci-PSP-SDK-03.20.00.13/filesys/home/root/lms2012"

#*** FILES ******************************************************************* 

bmp=".bmp"
xbm=".xbm"

rbf=".rbf"
rgf=".rgf"
rsf=".rsf"
raf=".raf"

#*** DO CLEAN UP *************************************************************

rm "${dir}"/*"${rbf}"
rm "${dir}"/*"${rsf}"

rm "${x86}"/"${path}"/"${dir}"/*"${rbf}"
rm "${x86}"/"${path}"/"${dir}"/*"${rsf}"

rm "${nfs}"/"${path}"/"${dir}"/*"${rbf}"
rm "${nfs}"/"${path}"/"${dir}"/*"${rsf}"

#*** DO COMPILE **************************************************************

app="Change Name"
echo -n Compile "  "../${dir}/${app}"      "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Debug"
echo -n Compile "  "../${dir}/${app}"            "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Display"
echo -n Compile "  "../${dir}/${app}"          "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Leds"
echo -n Compile "  "../${dir}/${app}"             "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Motors"
echo -n Compile "  "../${dir}/${app}"           "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="NoDebug"
echo -n Compile "  "../${dir}/${app}"          "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Performance"
echo -n Compile "  "../${dir}/${app}"      "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Power"
echo -n Compile "  "../${dir}/${app}"            "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="SDCard"
echo -n Compile "  "../${dir}/${app}"           "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Sensors"
echo -n Compile "  "../${dir}/${app}"          "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="Sound"
echo -n Compile "  "../${dir}/${app}"            "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="UnlockDatalog"
echo -n Compile "  "../${dir}/${app}"    "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

app="USlevel"
echo -n Compile "  "../${dir}/${app}"          "
${lms_to_rbf} "${app}" "${dir}"/"${app}""${rbf}"

#*** DO CONVERT **************************************************************

echo -n Convert and copy

#*** DO CONVERT SOUND ********************************************************

srcfile="Test"
cp "${srcfile}${rsf}" "${dir}"/"${srcfile}${rsf}"

#*** DO COPY IN PLACE ********************************************************

cp "${dir}"/*"${rbf}" "${x86}"/"${path}"/"${dir}"/
cp "${dir}"/*"${rsf}" "${x86}"/"${path}"/"${dir}"/

cp "${dir}"/*"${rbf}" "${nfs}"/"${path}"/"${dir}"/
cp "${dir}"/*"${rsf}" "${nfs}"/"${path}"/"${dir}"/

#cp "${dir}"/*"${rbf}" "${am1808}"/"${path}"/"${dir}"/
#cp "${dir}"/*"${rsf}" "${am1808}"/"${path}"/"${dir}"/

#*** DONE ********************************************************************

echo

