APP = ui
APP_PATH = sys

PROGRAMS = ui
GRAPHICS = mindstorms Ani1x screen playrecent_screen file_screen apps_screen \
           settings_screen 144x65_POP3 144x82_POP4
SOUNDS = Click DownloadSucces GeneralAlarm OverpowerAlert PowerDown Startup

screen_SOURCE = 89x178_MainMenuBottom
playrecent_screen_SOURCE = 178x26_PLAYLAST_TAB
file_screen_SOURCE = 178x26_FILE_TAB
apps_screen_SOURCE = 178x26_APPS_TAB
settings_screen_SOURCE = 178x26_SETTINGS_TAB

include ../rules.mk
