#! /bin/bash

#*** APPLICATION *************************************************************

path="sys"
app="ui"

#*** HOST ********************************************************************

lms_to_rbf="../adk/cmp"
xbm_to_rgf="../adk/bmp"
bmp_to_xbm="convert"

#*** TARGET ******************************************************************

am1808="../../lms2012/Linux_AM1808"
x86="../../lms2012/Linux_X86"
nfs="../../../../am1808/DaVinci-PSP-SDK-03.20.00.13/filesys/home/root/lms2012"

#*** FILES ******************************************************************* 

bmp=".bmp"
xbm=".xbm"

rbf=".rbf"
rgf=".rgf"
rsf=".rsf"
raf=".raf"

#*** DO CLEAN UP *************************************************************

if [ -e "${app}/*${rbf}" ]
then
  rm "${app}"/*"${rbf}"
fi

if [ -e "${app}/*${rgf}" ]
then
  rm "${app}"/*"${rgf}"
fi

if [ -e "${app}/*${rsf}" ]
then
  rm "${app}"/*"${rsf}"
fi

if [ -e "${x86}/${path}/${app}/*${rbf}" ]
then
  rm "${x86}"/"${path}"/"${app}"/*"${rbf}"
fi

if [ -e "${x86}/${path}/${app}/*${rgf}" ]
then
  rm "${x86}"/"${path}"/"${app}"/*"${rgf}"
fi

if [ -e "${x86}/${path}/${app}/*${rsf}" ]
then
  rm "${x86}"/"${path}"/"${app}"/*"${rsf}"
fi

if [ -e "${nfs}/${path}/${app}/*${rbf}" ]
then
  rm "${nfs}"/"${path}"/"${app}"/*"${rbf}"
fi

if [ -e "${nfs}/${path}/${app}/*${rgf}" ]
then
  rm "${nfs}"/"${path}"/"${app}"/*"${rgf}"
fi

if [ -e "${nfs}/${path}/${app}/*${rsf}" ]
then
  rm "${nfs}"/"${path}"/"${app}"/*"${rsf}"
fi

if [ -e "${am1808}/${path}/${app}/*${rbf}" ]
then
  rm "${am1808}"/"${path}"/"${app}"/*"${rbf}"
fi

if [ -e "${am1808}/${path}/${app}/*${rgf}" ]
then
  rm "${am1808}"/"${path}"/"${app}"/*"${rgf}"
fi

if [ -e "${am1808}/${path}/${app}/*${rsf}" ]
then
  rm "${am1808}"/"${path}"/"${app}"/*"${rsf}"
fi

#*** DO COMPILE **************************************************************

echo -n Compile "  "../${path}/${app}"                "
${lms_to_rbf} "${app}" "${app}"/"${app}""${rbf}"

#*** DO CONVERT **************************************************************

echo -n Convert and copy

#*** DO CONVERT GRAPHICS *****************************************************

srcfile="mindstorms"
dstfile="mindstorms"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="Ani1x"
dstfile="Ani1x"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="89x178_MainMenuBottom"
dstfile="screen"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="178x26_PLAYLAST_TAB"
dstfile="playrecent_screen"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="178x26_FILE_TAB"
dstfile="file_screen"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="178x26_APPS_TAB"
dstfile="apps_screen"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="178x26_SETTINGS_TAB"
dstfile="settings_screen"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${dstfile}"

srcfile="144x65_POP3"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${srcfile}"

srcfile="144x82_POP4"
${bmp_to_xbm} "${srcfile}${bmp}" "${app}"/bitmap"${xbm}"
${xbm_to_rgf} "${app}"/bitmap "${app}"/"${srcfile}"

#*** DO CONVERT SOUND ********************************************************

srcfile="Click"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

srcfile="DownloadSucces"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

srcfile="GeneralAlarm"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

srcfile="OverpowerAlert"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

srcfile="PowerDown"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

srcfile="Startup"
cp "${srcfile}${rsf}" "${app}"/"${srcfile}${rsf}"

#*** DO COPY IN PLACE ********************************************************

cp "${app}"/*"${rbf}" "${x86}"/"${path}"/"${app}"/
cp "${app}"/*"${rgf}" "${x86}"/"${path}"/"${app}"/
cp "${app}"/*"${rsf}" "${x86}"/"${path}"/"${app}"/

cp "${app}"/*"${rbf}" "${nfs}"/"${path}"/"${app}"/
cp "${app}"/*"${rgf}" "${nfs}"/"${path}"/"${app}"/
cp "${app}"/*"${rsf}" "${nfs}"/"${path}"/"${app}"/

cp "${app}"/*"${rbf}" "${am1808}"/"${path}"/"${app}"/
cp "${app}"/*"${rgf}" "${am1808}"/"${path}"/"${app}"/
cp "${app}"/*"${rsf}" "${am1808}"/"${path}"/"${app}"/

#*** DONE ********************************************************************

echo

