APP = SelfTest
APP_PATH = prjs
INSTALL_TO = X86

PROGRAMS = Run Test0101 Test0102 TestPrg1 TestPrg2 Test0103 Test0104 Test0105 \
           Test0106 Test0107 Test0108 Test0109 Test0110 Test0201 Test0202
PROGRAMS_TASM = TestPrg4

include ../rules.mk
