#!/bin/sh

if [ "x$1" = "x-a" ] || [ "x$1" = "x-A" ]; then
  if [ ! -f $OPKG_INTERCEPT_DIR/depmod ]; then
    echo "depmod -A" > $OPKG_INTERCEPT_DIR/depmod
    chmod +x $OPKG_INTERCEPT_DIR/depmod
  fi
  exit 0
fi

/sbin/depmod $*

