#! /bin/bash

path="prjs"
app="Demo"

#*** GENERIC CONSTANTS *******************************************************

gext=".rgf"
bext=".rbf"
am1808="../../lms2012/Linux_AM1808"
x86="../../lms2012/Linux_X86"

#*** COMPILE *****************************************************************

echo
echo -------------------------------------------------------------------------
echo Compiling ../${path}/${app}
echo

rm "${app}"/*.rbf
#rm "${app}"/*.rgf


../adk/asm "${app}"
cp "${app}""${bext}" "${app}"/
rm "${app}""${bext}"

#*** CONVERT ICON ************************************************************

#convert "${srcbitmap}" "${app}"/bitmap.xbm
#../adk/bmp "${app}"/bitmap "${app}"/icon




#*** COPY IN PLACE ***********************************************************

rm "${am1808}"/"${path}"/"${app}"/*.r?f
rm "${x86}"/"${path}"/"${app}"/*.r?f
cp "${app}"/*.r?f "${am1808}"/"${path}"/"${app}"/
cp "${app}"/*.r?f "${x86}"/"${path}"/"${app}"/
rm ../../../../am1808/DaVinci-PSP-SDK-03.20.00.13/filesys/home/root/lms2012/"${path}"/"${app}"/*.r?f
cp "${app}"/*.r?f ../../../../am1808/DaVinci-PSP-SDK-03.20.00.13/filesys/home/root/lms2012/"${path}"/"${app}"/

#rm -r "${am1808}"/"${path}"/"${app}"
#cp -r "${app}" "${am1808}"/"${path}"/
#rm -r "${x86}"/"${path}"/"${app}"
#cp -r "${app}" "${x86}"/"${path}"/




