APP = Bluetooth
APP_PATH = tools

PROGRAMS = Bluetooth
ICON = BluetoothIcon
GRAPHICS = 144x48_POP2 144x65_POP3 144x82_POP4 144x99_POP5 144x116_POP6 \
	   mode2
SOUNDS = GeneralAlarm Connect

include ../rules.mk
