#! /bin/sh

sync

var=$(printf 'HostStr=%s SerialStr=%s' $(cat /home/root/lms2012/sys/settings/BrickName) $(cat /home/root/lms2012/sys/settings/BTser))
echo $var > /home/root/lms2012/sys/settings/UsbInfo.dat

insmod ${PWD}/mod/d_iic.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_uart.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_power.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_pwm.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_ui.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_analog.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_usbdev.ko `cat /home/root/lms2012/sys/settings/UsbInfo.dat`
insmod ${PWD}/mod/d_usbhost.ko
insmod ${PWD}/mod/d_sound.ko `cat /home/root/lms2012/sys/settings/HwId`
insmod ${PWD}/mod/d_bt.ko `cat /home/root/lms2012/sys/settings/HwId`

chmod 666 /dev/lms_pwm
chmod 666 /dev/lms_motor
chmod 666 /dev/lms_analog
chmod 666 /dev/lms_dcm
chmod 666 /dev/lms_ui
chmod 666 /dev/lms_uart
chmod 666 /dev/lms_power
chmod 666 /dev/lms_usbdev
chmod 666 /dev/lms_usbhost
chmod 666 /dev/lms_sound
chmod 666 /dev/lms_iic
chmod 666 /dev/lms_bt

cd ..
ls -R > /dev/null
cd sys
