SOURCES = c_branch.c c_compare.c c_math.c c_move.c c_timer.c \
	  lms2012.c validate.c 
LIBS = -lrt -lusb-1.0 -ldbus-1 -lbluetooth -lm \
       -lc_com -lc_input -lc_memory -lc_output -lc_sound -lc_ui
SUBDIRS = c_com c_input c_memory c_output c_sound c_ui

TARGET = lms2012

CONF = Linux
ARCH = AM1808

include ../../open_first/rules.mk
