APP = Brick+Datalog
APP_PATH = apps

PROGRAMS = Brick+Datalog
ICON = 24x12_DLApp
GRAPHICS = 144x82_POP4 dl_PrtDetault dl_Rec dl_Set dl_RecH dl_SetH dl_Prt1 \
	   dl_Prt2 dl_Prt3 dl_Prt4 dl_PrtA dl_PrtB dl_PrtC dl_PrtD \
	   dl_Prt_All dl_Prt_Er dl_Prt_Un dl_count dl_mxave dl_NoDetails \
	   dlSetAccept dlSetAcceptH dl_GR0_1 dl_GR0_8 dl_GR0_10 dl_GR0_100 \
	   dl_GR0_250 dl_GRc100 dl_GRc180 dl_GRc450 dl_GR_TC dl_Highrate \
	   tdef t010 t020 t030 t040 t050 t060 t061 t070 t071 t080 t081 t160 \
	   t290 t291 t292 t300 t320 t321 t330 t331 t332 PE_input PE_output
SOUNDS = GeneralAlarm
ARCHIVE = y

tdef_SOURCE = other
t010_SOURCE = NXT_device
t020_SOURCE = NXT_device
t030_SOURCE = NXT_device
t040_SOURCE = NXT_device
t050_SOURCE = NXT_device
t060_SOURCE = temp_c
t061_SOURCE = temp_f
t070_SOURCE = lrg_motor_d
t071_SOURCE = lrg_motor
t080_SOURCE = med_motor_d
t081_SOURCE = med_motor
t160_SOURCE = touch
t290_SOURCE = color_ref
t291_SOURCE = color_amb
t292_SOURCE = color_col
t300_SOURCE = us_prox
t320_SOURCE = gyro_a
t321_SOURCE = gyro_rate
t330_SOURCE = ir_prox
t331_SOURCE = ir_bpos
t332_SOURCE = ir_bbut

include ../rules.mk
