APP = c_ui
INSTALL_TO = source

GRAPHICS_XBM = small_icons menu_icons normal_icons large_icons arrow_icons \
               small_font normal_font large_font tiny_font keyboardc keyboardn \
               keyboards mindstorms Ani1x Ani2x Ani3x Ani4x Ani5x Ani6x POP2 \
               POP3 PCApp

small_icons_SOURCE = 16x8_TopBar_Icons
menu_icons_SOURCE = 16x12_MenuItems
normal_icons_SOURCE = 24x12_Files_Folders_Settings
large_icons_SOURCE = 24x22_Yes_No_OFF_FILEOps
arrow_icons_SOURCE = 8x12_miniArrows
small_font_SOURCE = brick_font_2011_v1.3-bold
normal_font_SOURCE = brick_font_2011_v1.3-regular
large_font_SOURCE = brick_font_LARGE
tiny_font_SOURCE = small_font
keyboardc_SOURCE = KEY_CAPCHAR
keyboardn_SOURCE = KEY_NumSymb
keyboards_SOURCE = KEY_SmCHAR
mindstorms_SOURCE = mindstorms
POP2_SOURCE = 144x48_POP2
POP3_SOURCE = 144x65_POP3
PCApp_SOURCE = 24x12_PCApp

include ../rules.mk
